In [1]:
import pandas as pd

In [2]:
data ={
    'name':['naveen','krish','hitesh','telsuko'],
    'salary':[100,200,300,400],
    'mail_id': ['naveen@gmail.com','krish@gmail.com','hitesh@gmail.com','tulesuko@gmail.com'],
    'addres': ['bengaluru','bengaluru','bengaluru','mumbai'],
}

In [3]:
pd.DataFrame(data)

name  salary             mail_id     addres
0   naveen     100    naveen@gmail.com  bengaluru
1    krish     200     krish@gmail.com  bengaluru
2   hitesh     300    hitesh@gmail.com  bengaluru
3  telsuko     400  tulesuko@gmail.com     mumbai

In [4]:
pd.DataFrame(data,columns =[0,1,2,3])

Empty DataFrame
Columns: [0, 1, 2, 3]
Index: []

In [5]:
df=pd.DataFrame(data,index = [0,1,2,3])

In [6]:
df

name  salary             mail_id     addres
0   naveen     100    naveen@gmail.com  bengaluru
1    krish     200     krish@gmail.com  bengaluru
2   hitesh     300    hitesh@gmail.com  bengaluru
3  telsuko     400  tulesuko@gmail.com     mumbai

In [7]:
df.loc[5:6]

Empty DataFrame
Columns: [name, salary, mail_id, addres]
Index: []

In [8]:
df.iloc[5:6]

Empty DataFrame
Columns: [name, salary, mail_id, addres]
Index: []

In [9]:
df.iloc[1:3]

name  salary           mail_id     addres
1   krish     200   krish@gmail.com  bengaluru
2  hitesh     300  hitesh@gmail.com  bengaluru

In [10]:
df0=pd.DataFrame(data,index =['naveen','krish','hitesh','telsuko'])

In [11]:
df0

name  salary             mail_id     addres
naveen    naveen     100    naveen@gmail.com  bengaluru
krish      krish     200     krish@gmail.com  bengaluru
hitesh    hitesh     300    hitesh@gmail.com  bengaluru
telsuko  telsuko     400  tulesuko@gmail.com     mumbai

In [12]:
data1={
    'pf-nu': [1245323,535356,3265,6738],
    'income_tax' : [234,3324,65423,7432],
    'mobile_no':[23423,56432,3412445,32125],
    'courses':['ds','bigdata','web dev', 'blockchain']
}

In [13]:
df1 = pd.DataFrame(data1)

In [14]:
df1

pf-nu  income_tax  mobile_no     courses
0  1245323         234      23423          ds
1   535356        3324      56432     bigdata
2     3265       65423    3412445     web dev
3     6738        7432      32125  blockchain

In [15]:
df

name  salary             mail_id     addres
0   naveen     100    naveen@gmail.com  bengaluru
1    krish     200     krish@gmail.com  bengaluru
2   hitesh     300    hitesh@gmail.com  bengaluru
3  telsuko     400  tulesuko@gmail.com     mumbai

In [16]:
pd.concat([df,df1])

name  salary             mail_id     addres      pf-nu  income_tax  \
0   naveen   100.0    naveen@gmail.com  bengaluru        NaN         NaN   
1    krish   200.0     krish@gmail.com  bengaluru        NaN         NaN   
2   hitesh   300.0    hitesh@gmail.com  bengaluru        NaN         NaN   
3  telsuko   400.0  tulesuko@gmail.com     mumbai        NaN         NaN   
0      NaN     NaN                 NaN        NaN  1245323.0       234.0   
1      NaN     NaN                 NaN        NaN   535356.0      3324.0   
2      NaN     NaN                 NaN        NaN     3265.0     65423.0   
3      NaN     NaN                 NaN        NaN     6738.0      7432.0   

   mobile_no     courses  
0        NaN         NaN  
1        NaN         NaN  
2        NaN         NaN  
3        NaN         NaN  
0    23423.0          ds  
1    56432.0     bigdata  
2  3412445.0     web dev  
3    32125.0  blockchain

In [17]:
pd.concat([df,df1],axis =0)

# axis = 1 mean column wise operation is to perform
# axis = 0 means row wise operartion is to perform

name  salary             mail_id     addres      pf-nu  income_tax  \
0   naveen   100.0    naveen@gmail.com  bengaluru        NaN         NaN   
1    krish   200.0     krish@gmail.com  bengaluru        NaN         NaN   
2   hitesh   300.0    hitesh@gmail.com  bengaluru        NaN         NaN   
3  telsuko   400.0  tulesuko@gmail.com     mumbai        NaN         NaN   
0      NaN     NaN                 NaN        NaN  1245323.0       234.0   
1      NaN     NaN                 NaN        NaN   535356.0      3324.0   
2      NaN     NaN                 NaN        NaN     3265.0     65423.0   
3      NaN     NaN                 NaN        NaN     6738.0      7432.0   

   mobile_no     courses  
0        NaN         NaN  
1        NaN         NaN  
2        NaN         NaN  
3        NaN         NaN  
0    23423.0          ds  
1    56432.0     bigdata  
2  3412445.0     web dev  
3    32125.0  blockchain

In [18]:
pd.concat([df,df1],axis =0)



# axis = 1 mean column wise operation is to perform
# axis = 0 means row wise operartion is to perform

name  salary             mail_id     addres      pf-nu  income_tax  \
0   naveen   100.0    naveen@gmail.com  bengaluru        NaN         NaN   
1    krish   200.0     krish@gmail.com  bengaluru        NaN         NaN   
2   hitesh   300.0    hitesh@gmail.com  bengaluru        NaN         NaN   
3  telsuko   400.0  tulesuko@gmail.com     mumbai        NaN         NaN   
0      NaN     NaN                 NaN        NaN  1245323.0       234.0   
1      NaN     NaN                 NaN        NaN   535356.0      3324.0   
2      NaN     NaN                 NaN        NaN     3265.0     65423.0   
3      NaN     NaN                 NaN        NaN     6738.0      7432.0   

   mobile_no     courses  
0        NaN         NaN  
1        NaN         NaN  
2        NaN         NaN  
3        NaN         NaN  
0    23423.0          ds  
1    56432.0     bigdata  
2  3412445.0     web dev  
3    32125.0  blockchain

In [19]:
data2 ={
    0:['naveen','krish','hitesh','telsuko'],
    
    1:[100,200,300,400],
    
    2: ['naveen@gmail.com','krish@gmail.com','hitesh@gmail.com','tulesuko@gmail.com'],

    3: ['bengaluru','bengaluru','bengaluru','mumbai'],
}

In [20]:
data3={
    'a': [1245323,535356,3265,6738],
    'b' : [234,3324,65423,7432],
    'c': [423,56432,3412445,32125],
    'd' :['ds','bigdata','web dev', 'blockchain']
}

In [21]:
df2 = pd.DataFrame(data2)

In [22]:
df2

0    1                   2          3
0   naveen  100    naveen@gmail.com  bengaluru
1    krish  200     krish@gmail.com  bengaluru
2   hitesh  300    hitesh@gmail.com  bengaluru
3  telsuko  400  tulesuko@gmail.com     mumbai

In [23]:
df3 =pd.DataFrame(data3)

In [24]:
df3

a      b        c           d
0  1245323    234      423          ds
1   535356   3324    56432     bigdata
2     3265  65423  3412445     web dev
3     6738   7432    32125  blockchain

In [25]:
pd.concat([df2,df3])

0      1                   2          3          a        b  \
0   naveen  100.0    naveen@gmail.com  bengaluru        NaN      NaN   
1    krish  200.0     krish@gmail.com  bengaluru        NaN      NaN   
2   hitesh  300.0    hitesh@gmail.com  bengaluru        NaN      NaN   
3  telsuko  400.0  tulesuko@gmail.com     mumbai        NaN      NaN   
0      NaN    NaN                 NaN        NaN  1245323.0    234.0   
1      NaN    NaN                 NaN        NaN   535356.0   3324.0   
2      NaN    NaN                 NaN        NaN     3265.0  65423.0   
3      NaN    NaN                 NaN        NaN     6738.0   7432.0   

           c           d  
0        NaN         NaN  
1        NaN         NaN  
2        NaN         NaN  
3        NaN         NaN  
0      423.0          ds  
1    56432.0     bigdata  
2  3412445.0     web dev  
3    32125.0  blockchain

In [26]:
data4 = {
    'emp_id':[101,102,103,104,105],
    'salary': [234,345,200,400,700],
    'pf':[23,34,56,78,25],
}

In [27]:
data5 = {
    'emp_id':[101,102,103,105,106],
    'mobile_no': [34562,123453,123452,75332,6567],
    'house_no': [345,423,231,234,75],
}

In [28]:
df4 = pd.DataFrame(data4)

In [29]:
df4

emp_id  salary  pf
0     101     234  23
1     102     345  34
2     103     200  56
3     104     400  78
4     105     700  25

In [30]:
df5 = pd.DataFrame(data5)

In [31]:
df5


emp_id  mobile_no  house_no
0     101      34562       345
1     102     123453       423
2     103     123452       231
3     105      75332       234
4     106       6567        75

In [32]:
pd.merge(df4,df5)

# merge operation

emp_id  salary  pf  mobile_no  house_no
0     101     234  23      34562       345
1     102     345  34     123453       423
2     103     200  56     123452       231
3     105     700  25      75332       234

In [33]:
pd.merge(df4,df5)


emp_id  salary  pf  mobile_no  house_no
0     101     234  23      34562       345
1     102     345  34     123453       423
2     103     200  56     123452       231
3     105     700  25      75332       234

In [34]:
pd.merge(df4,df5, how ='right')


emp_id  salary    pf  mobile_no  house_no
0     101   234.0  23.0      34562       345
1     102   345.0  34.0     123453       423
2     103   200.0  56.0     123452       231
3     105   700.0  25.0      75332       234
4     106     NaN   NaN       6567        75

In [35]:
df4

emp_id  salary  pf
0     101     234  23
1     102     345  34
2     103     200  56
3     104     400  78
4     105     700  25

In [36]:
df5

emp_id  mobile_no  house_no
0     101      34562       345
1     102     123453       423
2     103     123452       231
3     105      75332       234
4     106       6567        75

In [37]:
pd.merge(df4,df5, how ='right', on = 'emp_id')

emp_id  salary    pf  mobile_no  house_no
0     101   234.0  23.0      34562       345
1     102   345.0  34.0     123453       423
2     103   200.0  56.0     123452       231
3     105   700.0  25.0      75332       234
4     106     NaN   NaN       6567        75

In [38]:
data6 = {
    'emp_id1':[101,102,103,104],
    'salary': [234,345,200,400],
    'pf':[23,34,56,78],
}
data7 = {
    'emp_id2':[101,102,103,105],
    'mobile_no': [34562,123453,123452,75332],
    'house_no': [345,423,231,234],
}

In [39]:
df6=pd.DataFrame(data6)

In [40]:
df7=pd.DataFrame(data7)

In [41]:
df6

emp_id1  salary  pf
0      101     234  23
1      102     345  34
2      103     200  56
3      104     400  78

In [42]:
df7

emp_id2  mobile_no  house_no
0      101      34562       345
1      102     123453       423
2      103     123452       231
3      105      75332       234

In [43]:
pd.merge(df6,df7)

MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False

In [44]:
pd.merge(df6,df7, left_on ='emp_id1', right_on = 'emp_id2')

# use ' ', not " ", it will throw you an error

emp_id1  salary  pf  emp_id2  mobile_no  house_no
0      101     234  23      101      34562       345
1      102     345  34      102     123453       423
2      103     200  56      103     123452       231

In [45]:
pd.merge(df6,df7, left_on ='emp_id1', right_on = 'emp_id2', how = 'inner')


emp_id1  salary  pf  emp_id2  mobile_no  house_no
0      101     234  23      101      34562       345
1      102     345  34      102     123453       423
2      103     200  56      103     123452       231

In [46]:
data8 = {
    'emp_id':[101,102,103,104],
    'salary': [234,345,200,400],
    'pf':[23,34,56,78]
}
data9 = {
    'emp_id':[101,102,103,105],
    'salary': [34562,123453,123452,75332],
    'house_no': [345,423,231,234]
}

In [47]:
df8 = pd.DataFrame(data8)

In [48]:
df9 = pd.DataFrame(data9)

In [49]:
df8

emp_id  salary  pf
0     101     234  23
1     102     345  34
2     103     200  56
3     104     400  78

In [50]:
df9

emp_id  salary  house_no
0     101   34562       345
1     102  123453       423
2     103  123452       231
3     105   75332       234

In [51]:
pd.merge(df8,df9)


Empty DataFrame
Columns: [emp_id, salary, pf, house_no]
Index: []

In [52]:
data10 = {
    'emp_id1':[101,102,103,104],
    'salary1': [234,345,200,400],
    'pf':[23,34,56,78]
}
data11 = {
    'emp_id2':[101,102,103,105,123],
    'salary2': [34562,123453,123452,75332,55646],
    'house_no': [345,423,231,234,754535]
}

In [53]:
df10 = pd.DataFrame(data10)

In [54]:
df10

emp_id1  salary1  pf
0      101      234  23
1      102      345  34
2      103      200  56
3      104      400  78

In [55]:
df11 = pd.DataFrame(data11)

In [56]:
df11

emp_id2  salary2  house_no
0      101    34562       345
1      102   123453       423
2      103   123452       231
3      105    75332       234
4      123    55646    754535

In [57]:
pd.merge(df10,df11, left_on='emp_id1', right_on='emp_id2')

emp_id1  salary1  pf  emp_id2  salary2  house_no
0      101      234  23      101    34562       345
1      102      345  34      102   123453       423
2      103      200  56      103   123452       231

In [58]:
df10 = pd.DataFrame(data10,index=['a','b','c','d'])

In [59]:
df11 = pd.DataFrame(data11,index=['a','b','d','e','f'])

In [60]:
df11

emp_id2  salary2  house_no
a      101    34562       345
b      102   123453       423
d      103   123452       231
e      105    75332       234
f      123    55646    754535

In [61]:
df10

emp_id1  salary1  pf
a      101      234  23
b      102      345  34
c      103      200  56
d      104      400  78

In [62]:
df10.join(df11)

emp_id1  salary1  pf  emp_id2   salary2  house_no
a      101      234  23    101.0   34562.0     345.0
b      102      345  34    102.0  123453.0     423.0
c      103      200  56      NaN       NaN       NaN
d      104      400  78    103.0  123452.0     231.0

In [63]:
df_sales =pd.read_csv(r"C:\Users\SVKUSER\Downloads\sales_data_final.csv")

In [64]:
df_sales

order_id  order_date ship_date       ship_mode  \
0         AG-2011-2040    1/1/2011  1/6/2011  Standard Class   
1        IN-2011-47883    1/1/2011  1/8/2011  Standard Class   
2         HU-2011-1220    1/1/2011  1/5/2011    Second Class   
3      IT-2011-3647632    1/1/2011  1/5/2011    Second Class   
4        IN-2011-47883    1/1/2011  1/8/2011  Standard Class   
...                ...         ...       ...             ...   
51285   CA-2014-115427  12/31/2014  1/4/2015  Standard Class   
51286     MO-2014-2560  12/31/2014  1/5/2015  Standard Class   
51287   MX-2014-110527  12/31/2014  1/2/2015    Second Class   
51288   MX-2014-114783  12/31/2014  1/6/2015  Standard Class   
51289   CA-2014-156720  12/31/2014  1/4/2015  Standard Class   

          customer_name      segment             state        country  market  \
0       Toby Braunhardt     Consumer       Constantine        Algeria  Africa   
1           Joseph Holt     Consumer   New South Wales      Australia    APAC   
2         Annie Thurman     Consumer          Budapest        Hungary    EMEA   
3          Eugene Moren  Home Office         Stockholm         Sweden      EU   
4           Joseph Holt     Consumer   New South Wales      Australia    APAC   
...                 ...          ...               ...            ...     ...   
51285        Erica Bern    Corporate        California  United States      US   
51286         Liz Preis     Consumer  Souss-Massa-Draƒ        Morocco  Africa   
51287  Charlotte Melton     Consumer           Managua      Nicaragua   LATAM   
51288     Tamara Dahlen     Consumer         Chihuahua         Mexico   LATAM   
51289     Jill Matthias     Consumer          Colorado  United States      US   

        region  ...         category sub_category  \
0       Africa  ...  Office Supplies      Storage   
1      Oceania  ...  Office Supplies     Supplies   
2         EMEA  ...  Office Supplies      Storage   
3        North  ...  Office Supplies        Paper   
4      Oceania  ...        Furniture  Furnishings   
...        ...  ...              ...          ...   
51285     West  ...  Office Supplies      Binders   
51286   Africa  ...  Office Supplies      Binders   
51287  Central  ...  Office Supplies       Labels   
51288    North  ...  Office Supplies       Labels   
51289     West  ...  Office Supplies    Fasteners   

                                          product_name sales quantity  \
0                                  Tenex Lockers, Blue   408        2   
1                             Acme Trimmer, High Speed   120        3   
2                              Tenex Box, Single Width    66        4   
3                          Enermax Note Cards, Premium    45        3   
4                           Eldon Light Bulb, Duo Pack   114        5   
...                                                ...   ...      ...   
51285  Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl    14        2   
51286          Wilson Jones Hole Reinforcements, Clear     4        1   
51287           Hon Color Coded Labels, 5000 Label Set    26        3   
51288           Hon Legal Exhibit Labels, Alphabetical     7        1   
51289                              Bagged Rubber Bands     3        3   

       discount    profit  shipping_cost  order_priority  year  
0           0.0  106.1400          35.46          Medium  2011  
1           0.1   36.0360           9.72          Medium  2011  
2           0.0   29.6400           8.17            High  2011  
3           0.5  -26.0550           4.82            High  2011  
4           0.1   37.7700           4.70          Medium  2011  
...         ...       ...            ...             ...   ...  
51285       0.2    4.5188           0.89          Medium  2014  
51286       0.0    0.4200           0.49          Medium  2014  
51287       0.0   12.3600           0.35          Medium  2014  
51288       0.0    0.5600           0.20          Medium  2014  
51289       0.2   -0.6048           0.17   

In [66]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ...  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...   
3  Home Office        Stockholm     Sweden      EU    North  ...   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   

          category sub_category                 product_name sales quantity  \
0  Office Supplies      Storage          Tenex Lockers, Blue   408        2   
1  Office Supplies     Supplies     Acme Trimmer, High Speed   120        3   
2  Office Supplies      Storage      Tenex Box, Single Width    66        4   
3  Office Supplies        Paper  Enermax Note Cards, Premium    45        3   
4        Furniture  Furnishings   Eldon Light Bulb, Duo Pack   114        5   

   discount   profit  shipping_cost  order_priority  year  
0       0.0  106.140          35.46          Medium  2011  
1       0.1   36.036           9.72          Medium  2011  
2       0.0   29.640           8.17            High  2011  
3       0.5  -26.055           4.82            High  2011  
4       0.1   37.770           4.70          Medium  2011  

[5 rows x 21 columns]

In [68]:
def profit_flag(a):
    if a >= 0:
        return 'positive'
    else:
        return 'negative'

In [69]:
profit_flag(-45)

'negative'

In [70]:
profit_flag(45)

'positive'

In [71]:
df_sales['flage_profit'] = df_sales['profit'].apply(profit_flag)

In [83]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... sales  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   408   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   120   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...    66   
3  Home Office        Stockholm     Sweden      EU    North  ...    45   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   114   

  quantity discount   profit shipping_cost  order_priority  year  \
0        2      0.0  106.140         35.46          Medium  2011   
1        3      0.1   36.036          9.72          Medium  2011   
2        4      0.0   29.640          8.17            High  2011   
3        3      0.5  -26.055          4.82            High  2011   
4        5      0.1   37.770          4.70          Medium  2011   

   flage_profit  len_cust_name company_name  
0      positive             15           14  
1      positive             11           14  
2      positive             13           12  
3      negative             12           12  
4      positive             11           14  

[5 rows x 24 columns]

In [85]:
df_sales['len_cus_name'] = df_sales['customer_name'].apply(len)

In [88]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... quantity  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...        2   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...        3   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...        4   
3  Home Office        Stockholm     Sweden      EU    North  ...        3   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...        5   

  discount   profit shipping_cost order_priority  year  flage_profit  \
0      0.0  106.140         35.46         Medium  2011      positive   
1      0.1   36.036          9.72         Medium  2011      positive   
2      0.0   29.640          8.17           High  2011      positive   
3      0.5  -26.055          4.82           High  2011      negative   
4      0.1   37.770          4.70         Medium  2011      positive   

   len_cust_name  company_name len_cus_name  
0             15            14           15  
1             11            14           11  
2             13            12           13  
3             12            12           12  
4             11            14           11  

[5 rows x 25 columns]

In [89]:
def quantity_flag(a):
    if a < 10:
        return 'low'
    elif a >10 and a <20:
        return 'medium'
    else:
        return 'high'

In [90]:
quantity_flag(30)

'high'

In [91]:
df_sales['flag_quantity'] = df_sales['quantity'].apply(quantity_flag)

In [97]:
df_sales.head(20)

order_id order_date ship_date       ship_mode      customer_name  \
0      AG-2011-2040   1/1/2011  1/6/2011  Standard Class    Toby Braunhardt   
1     IN-2011-47883   1/1/2011  1/8/2011  Standard Class        Joseph Holt   
2      HU-2011-1220   1/1/2011  1/5/2011    Second Class      Annie Thurman   
3   IT-2011-3647632   1/1/2011  1/5/2011    Second Class       Eugene Moren   
4     IN-2011-47883   1/1/2011  1/8/2011  Standard Class        Joseph Holt   
5     IN-2011-47883   1/1/2011  1/8/2011  Standard Class        Joseph Holt   
6      CA-2011-1510   1/2/2011  1/6/2011  Standard Class    Magdelene Morse   
7     IN-2011-79397   1/3/2011  1/3/2011        Same Day        Kean Nguyen   
8     ID-2011-80230   1/3/2011  1/9/2011  Standard Class       Ken Lonsdale   
9      IZ-2011-4680   1/3/2011  1/7/2011  Standard Class   Lindsay Williams   
10    IN-2011-65159   1/3/2011  1/7/2011    Second Class       Larry Blacks   
11    IN-2011-65159   1/3/2011  1/7/2011    Second Class       Larry Blacks   
12  ES-2011-4869686   1/3/2011  1/7/2011  Standard Class  Dorothy Dickinson   
13    IN-2011-33652   1/3/2011  1/9/2011  Standard Class      Dennis Pardue   
14    ID-2011-80230   1/3/2011  1/9/2011  Standard Class       Ken Lonsdale   
15   MX-2011-160234   1/3/2011  1/7/2011  Standard Class   Stewart Visinsky   
16      IR-2011-770   1/3/2011  1/7/2011  Standard Class      Jas O'Carroll   
17    ID-2011-80230   1/3/2011  1/9/2011  Standard Class       Ken Lonsdale   
18    ID-2011-80230   1/3/2011  1/9/2011  Standard Class       Ken Lonsdale   
19    ID-2011-12596   1/3/2011  1/8/2011  Standard Class       Chris McAfee   

        segment              state         country  market          region  \
0      Consumer        Constantine         Algeria  Africa          Africa   
1      Consumer    New South Wales       Australia    APAC         Oceania   
2      Consumer           Budapest         Hungary    EMEA            EMEA   
3   Home Office          Stockholm          Sweden      EU           North   
4      Consumer    New South Wales       Australia    APAC         Oceania   
5      Consumer    New South Wales       Australia    APAC         Oceania   
6      Consumer            Ontario          Canada  Canada          Canada   
7     Corporate    New South Wales       Australia    APAC         Oceania   
8      Consumer           Auckland     New Zealand    APAC         Oceania   
9     Corporate             Ninawa            Iraq    EMEA            EMEA   
10     Consumer   National Capital     Philippines    APAC  Southeast Asia   
11     Consumer   National Capital     Philippines    APAC  Southeast Asia   
12     Consumer            England  United Kingdom      EU           North   
13  Home Office            Sarawak        Malaysia    APAC  Southeast Asia   
14     Consumer           Auckland     New Zealand    APAC         Oceania   
15     Consumer          Guatemala       Guatemala   LATAM         Central   
16     Consumer               Yazd            Iran    EMEA            EMEA   
17     Consumer           Auckland     New Zealand    APAC         Oceania   
18     Consumer           Auckland     New Zealand    APAC         Oceania   
19     Consumer  Nakhon Ratchasima        Thailand    APAC  Southeast Asia   

    ... discount    profit shipping_cost order_priority  year  flage_profit  \
0   ...     0.00  106.1400         35.46         Medium  2011      positive   
1   ...     0.10   36.0360          9.72         Medium  2011      positive   
2   ...     0.00   29.6400          8.17           High  2011      positive   
3   ...     0.50  -26.0550          4.82           High  2011      negative   
4   ...     0.10   37.7700          4.70         Medium  2011      positive   
5   ...     0.10   15.3420          1.80         Medium  2011      positive   
6   ...     0.00    3.1200         24.10         Medium  2011      positive   
7   ...     0.10  110.4120        125.32       Critical  2011      positive   
8

In [99]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... discount  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...      0.0   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...      0.1   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...      0.0   
3  Home Office        Stockholm     Sweden      EU    North  ...      0.5   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...      0.1   

    profit shipping_cost order_priority  year  flage_profit  len_cust_name  \
0  106.140         35.46         Medium  2011      positive             15   
1   36.036          9.72         Medium  2011      positive             11   
2   29.640          8.17           High  2011      positive             13   
3  -26.055          4.82           High  2011      negative             12   
4   37.770          4.70         Medium  2011      positive             11   

   company_name  len_cus_name flag_quantity  
0            14            15           low  
1            14            11           low  
2            12            13           low  
3            12            12           low  
4            14            11           low  

[5 rows x 26 columns]

In [102]:
df_sales['square_quantity'] = df_sales['quantity'].apply(lambda a : a**2)

In [103]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ...   profit  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...  106.140   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   36.036   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...   29.640   
3  Home Office        Stockholm     Sweden      EU    North  ...  -26.055   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   37.770   

  shipping_cost order_priority  year flage_profit  len_cust_name  \
0         35.46         Medium  2011     positive             15   
1          9.72         Medium  2011     positive             11   
2          8.17           High  2011     positive             13   
3          4.82           High  2011     negative             12   
4          4.70         Medium  2011     positive             11   

   company_name  len_cus_name  flag_quantity square_quantity  
0            14            15            low               4  
1            14            11            low               9  
2            12            13            low              16  
3            12            12            low               9  
4            14            11            low              25  

[5 rows x 27 columns]

# numpy is nothing but to perform the mathamatical operation we use numpuy

# before it was matlab but later this entire matlab was converted or moved to numpuy!!

##  NumPy is a Python library used for working with arrays.

### It also has functions for working in domain of linear algebra, fourier transform, and matrices.

### NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

### NumPy stands for Numerical Python.

# numpy

In [104]:
import numpy as np

In [107]:
np.array([2,3,4,5,6])

array([2, 3, 4, 5, 6])

In [109]:
type(np.array([2,3,4,5,6]))

numpy.ndarray

In [117]:
np.array([[2,3,4],[4,5,6]])

array([[2, 3, 4],
       [4, 5, 6]])

In [119]:
np.array([[1,2,3,4],[2,3,4,5]])

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [121]:
l = [[1,2,3,4],[2,3,4,5]]

In [123]:
l[0]

[1, 2, 3, 4]

In [124]:
l[0][0]

1

In [126]:
a = np.array([3,4,5,6],ndmin = 5)

In [127]:
a

array([[[[[3, 4, 5, 6]]]]])

In [128]:
b = np.array([3,4,5,6],ndmin = 3)

In [129]:
b

array([[[3, 4, 5, 6]]])

In [130]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [131]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [132]:
arr.ndim # dimention of an array

2

In [135]:
np.random.randint(1,10,(4,4)) 
# (random.randint)-This function is used to set random dataset between 1 - 10 , where  dimention is (4,4) whre 4 rows and 4 columns

array([[4, 4, 4, 5],
       [9, 7, 3, 5],
       [2, 2, 3, 4],
       [1, 2, 1, 6]])

In [136]:
np.random.randint(1,10,(4,4,2)) 

# we have (4,4,2) = 4 rows X 2 columns, four times
# EX: (4,4,2) = we have to take the value from the last like 4 rows X 2 columns 4 times.

""" HERE (4,4,2) 4 rows X 2 columns represent 4 times:

    4X2 [--]  these - - are filled with random numbers between 1 - 10 
        [--]
        [--]
        [--]
    
    4x2 [--]  these - - are filled with random numbers between 1 - 10
        [--]
        [--]
        [--]
        
        
    4X2 [--] these - - are filled with random numbers between 1 - 10
        [--]
        [--]
        [--]
        
        
    4x2 [--]
        [--]
        [--]
        [--]   these - - are filled with random numbers between 1 - 10"""

# this the actual meanning of np.random.randint(1,10,(4,4,2))

array([[[6, 2],
        [5, 7],
        [1, 7],
        [1, 9]],

       [[2, 8],
        [2, 8],
        [7, 5],
        [6, 5]],

       [[2, 8],
        [9, 3],
        [2, 6],
        [1, 1]],

       [[7, 2],
        [3, 7],
        [2, 6],
        [9, 1]]])